### ISSUE TITLE
Add support for video tracks

### ISSUE THREAD

**Issue by zachsaw** [DeadlyEmbrace/MPDN_RemoteControl#19]
MPDN has support for video track selection for some time now so I was wondering if you could add that to the remote too?

**Comment by DeadlyEmbrace** [comment]
Sure thing, I've been meaning to catch up again but got a little stuck in a personal project.
Will make some time over the next week or two to add that as well as do some general cleanup.

**Comment by zachsaw** [comment]
Thank you so much!

**Comment by DeadlyEmbrace** [comment]
Sorry, thing have been a bit hectic the past two weeks. Was hunting for a new job.
Anyhow, gonna get around to this (and hopefully general Remote Control improvements) over the weekend.

**Comment by zachsaw** [comment]
No problem at all. No rush really. :)

And good luck with the job hunting!

**Comment by DeadlyEmbrace** [comment]
Sorry that things have been dragging for so long, was wrapping up with my old company and on leave last week. From this week things should return to normal so I should finally be able to work on the remote again.
Do you perhaps have a multi-video track sample I can use? I don't have any (and I prefer to test with a working sample rather than trusting that I coded it correctly)

**Comment by zachsaw** [comment]
No worries mate! Hope you've moved on to greener pastures?
In regards to the multitrack video, I've sent you a Doom9 PM.

**Comment by DeadlyEmbrace** [comment]
I did indeed. :)
Thanks, I'll take a look at it sometime this week/weekend.
